/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedWaitlistRouteImport } from './routes/_authenticated/waitlist'
import { Route as AuthenticatedTransportRouteImport } from './routes/_authenticated/transport'
import { Route as AuthenticatedSpeakersRouteImport } from './routes/_authenticated/speakers'
import { Route as AuthenticatedScheduleRouteImport } from './routes/_authenticated/schedule'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedNetworkRouteImport } from './routes/_authenticated/network'
import { Route as AuthenticatedNearbyRouteImport } from './routes/_authenticated/nearby'
import { Route as AuthenticatedMoreRouteImport } from './routes/_authenticated/more'
import { Route as AuthenticatedMapRouteImport } from './routes/_authenticated/map'
import { Route as AuthenticatedMaidguideRouteImport } from './routes/_authenticated/maidguide'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedFaqRouteImport } from './routes/_authenticated/faq'
import { Route as AuthenticatedEmergencyRouteImport } from './routes/_authenticated/emergency'
import { Route as AuthenticatedDirectionsRouteImport } from './routes/_authenticated/directions'
import { Route as AuthenticatedConciergeRouteImport } from './routes/_authenticated/concierge'
import { Route as AuthenticatedChatbotRouteImport } from './routes/_authenticated/chatbot'
import { Route as AuthenticatedAnnouncementsRouteImport } from './routes/_authenticated/announcements'
import { Route as AuthenticatedAccommodationRouteImport } from './routes/_authenticated/accommodation'
import { Route as AuthenticatedAboutRouteImport } from './routes/_authenticated/about'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedConciergeIndexRouteImport } from './routes/_authenticated/concierge.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedSpeakersSpeakerIdRouteImport } from './routes/_authenticated/speakers.$speakerId'
import { Route as AuthenticatedScheduleSessionIdRouteImport } from './routes/_authenticated/schedule.$sessionId'
import { Route as AuthenticatedNetworkUserIdRouteImport } from './routes/_authenticated/network.$userId'
import { Route as AuthenticatedConciergeUsherRouteImport } from './routes/_authenticated/concierge.usher'
import { Route as AuthenticatedConciergeOrdersRouteImport } from './routes/_authenticated/concierge.orders'
import { Route as AuthenticatedConciergeFoodRouteImport } from './routes/_authenticated/concierge.food'
import { Route as AuthenticatedAdminUshersRouteImport } from './routes/_authenticated/admin/ushers'
import { Route as AuthenticatedAdminSpeakersRouteImport } from './routes/_authenticated/admin/speakers'
import { Route as AuthenticatedAdminSessionsRouteImport } from './routes/_authenticated/admin/sessions'
import { Route as AuthenticatedAdminOrdersRouteImport } from './routes/_authenticated/admin/orders'
import { Route as AuthenticatedAdminMenuRouteImport } from './routes/_authenticated/admin/menu'
import { Route as AuthenticatedAdminEmergencyRouteImport } from './routes/_authenticated/admin/emergency'
import { Route as AuthenticatedAdminAnnouncementsRouteImport } from './routes/_authenticated/admin/announcements'
import { Route as AuthenticatedAdminAccommodationsRouteImport } from './routes/_authenticated/admin/accommodations'
import { Route as AuthenticatedNetworkRoomRoomIdRouteImport } from './routes/_authenticated/network.room.$roomId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWaitlistRoute = AuthenticatedWaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTransportRoute = AuthenticatedTransportRouteImport.update({
  id: '/transport',
  path: '/transport',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSpeakersRoute = AuthenticatedSpeakersRouteImport.update({
  id: '/speakers',
  path: '/speakers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScheduleRoute = AuthenticatedScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNetworkRoute = AuthenticatedNetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNearbyRoute = AuthenticatedNearbyRouteImport.update({
  id: '/nearby',
  path: '/nearby',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMoreRoute = AuthenticatedMoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMapRoute = AuthenticatedMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMaidguideRoute = AuthenticatedMaidguideRouteImport.update({
  id: '/maidguide',
  path: '/maidguide',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFaqRoute = AuthenticatedFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmergencyRoute = AuthenticatedEmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDirectionsRoute = AuthenticatedDirectionsRouteImport.update({
  id: '/directions',
  path: '/directions',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConciergeRoute = AuthenticatedConciergeRouteImport.update({
  id: '/concierge',
  path: '/concierge',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatbotRoute = AuthenticatedChatbotRouteImport.update({
  id: '/chatbot',
  path: '/chatbot',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnnouncementsRoute =
  AuthenticatedAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccommodationRoute =
  AuthenticatedAccommodationRouteImport.update({
    id: '/accommodation',
    path: '/accommodation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAboutRoute = AuthenticatedAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConciergeIndexRoute =
  AuthenticatedConciergeIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedConciergeRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedSpeakersSpeakerIdRoute =
  AuthenticatedSpeakersSpeakerIdRouteImport.update({
    id: '/$speakerId',
    path: '/$speakerId',
    getParentRoute: () => AuthenticatedSpeakersRoute,
  } as any)
const AuthenticatedScheduleSessionIdRoute =
  AuthenticatedScheduleSessionIdRouteImport.update({
    id: '/$sessionId',
    path: '/$sessionId',
    getParentRoute: () => AuthenticatedScheduleRoute,
  } as any)
const AuthenticatedNetworkUserIdRoute =
  AuthenticatedNetworkUserIdRouteImport.update({
    id: '/$userId',
    path: '/$userId',
    getParentRoute: () => AuthenticatedNetworkRoute,
  } as any)
const AuthenticatedConciergeUsherRoute =
  AuthenticatedConciergeUsherRouteImport.update({
    id: '/usher',
    path: '/usher',
    getParentRoute: () => AuthenticatedConciergeRoute,
  } as any)
const AuthenticatedConciergeOrdersRoute =
  AuthenticatedConciergeOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedConciergeRoute,
  } as any)
const AuthenticatedConciergeFoodRoute =
  AuthenticatedConciergeFoodRouteImport.update({
    id: '/food',
    path: '/food',
    getParentRoute: () => AuthenticatedConciergeRoute,
  } as any)
const AuthenticatedAdminUshersRoute =
  AuthenticatedAdminUshersRouteImport.update({
    id: '/ushers',
    path: '/ushers',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSpeakersRoute =
  AuthenticatedAdminSpeakersRouteImport.update({
    id: '/speakers',
    path: '/speakers',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSessionsRoute =
  AuthenticatedAdminSessionsRouteImport.update({
    id: '/sessions',
    path: '/sessions',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminOrdersRoute =
  AuthenticatedAdminOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminMenuRoute = AuthenticatedAdminMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminEmergencyRoute =
  AuthenticatedAdminEmergencyRouteImport.update({
    id: '/emergency',
    path: '/emergency',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAnnouncementsRoute =
  AuthenticatedAdminAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAccommodationsRoute =
  AuthenticatedAdminAccommodationsRouteImport.update({
    id: '/accommodations',
    path: '/accommodations',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedNetworkRoomRoomIdRoute =
  AuthenticatedNetworkRoomRoomIdRouteImport.update({
    id: '/room/$roomId',
    path: '/room/$roomId',
    getParentRoute: () => AuthenticatedNetworkRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/about': typeof AuthenticatedAboutRoute
  '/accommodation': typeof AuthenticatedAccommodationRoute
  '/announcements': typeof AuthenticatedAnnouncementsRoute
  '/chatbot': typeof AuthenticatedChatbotRoute
  '/concierge': typeof AuthenticatedConciergeRouteWithChildren
  '/directions': typeof AuthenticatedDirectionsRoute
  '/emergency': typeof AuthenticatedEmergencyRoute
  '/faq': typeof AuthenticatedFaqRoute
  '/home': typeof AuthenticatedHomeRoute
  '/maidguide': typeof AuthenticatedMaidguideRoute
  '/map': typeof AuthenticatedMapRoute
  '/more': typeof AuthenticatedMoreRoute
  '/nearby': typeof AuthenticatedNearbyRoute
  '/network': typeof AuthenticatedNetworkRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/schedule': typeof AuthenticatedScheduleRouteWithChildren
  '/speakers': typeof AuthenticatedSpeakersRouteWithChildren
  '/transport': typeof AuthenticatedTransportRoute
  '/waitlist': typeof AuthenticatedWaitlistRoute
  '/api/chat': typeof ApiChatRoute
  '/admin/accommodations': typeof AuthenticatedAdminAccommodationsRoute
  '/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/admin/emergency': typeof AuthenticatedAdminEmergencyRoute
  '/admin/menu': typeof AuthenticatedAdminMenuRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/sessions': typeof AuthenticatedAdminSessionsRoute
  '/admin/speakers': typeof AuthenticatedAdminSpeakersRoute
  '/admin/ushers': typeof AuthenticatedAdminUshersRoute
  '/concierge/food': typeof AuthenticatedConciergeFoodRoute
  '/concierge/orders': typeof AuthenticatedConciergeOrdersRoute
  '/concierge/usher': typeof AuthenticatedConciergeUsherRoute
  '/network/$userId': typeof AuthenticatedNetworkUserIdRoute
  '/schedule/$sessionId': typeof AuthenticatedScheduleSessionIdRoute
  '/speakers/$speakerId': typeof AuthenticatedSpeakersSpeakerIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/concierge/': typeof AuthenticatedConciergeIndexRoute
  '/network/room/$roomId': typeof AuthenticatedNetworkRoomRoomIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/about': typeof AuthenticatedAboutRoute
  '/accommodation': typeof AuthenticatedAccommodationRoute
  '/announcements': typeof AuthenticatedAnnouncementsRoute
  '/chatbot': typeof AuthenticatedChatbotRoute
  '/directions': typeof AuthenticatedDirectionsRoute
  '/emergency': typeof AuthenticatedEmergencyRoute
  '/faq': typeof AuthenticatedFaqRoute
  '/home': typeof AuthenticatedHomeRoute
  '/maidguide': typeof AuthenticatedMaidguideRoute
  '/map': typeof AuthenticatedMapRoute
  '/more': typeof AuthenticatedMoreRoute
  '/nearby': typeof AuthenticatedNearbyRoute
  '/network': typeof AuthenticatedNetworkRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/schedule': typeof AuthenticatedScheduleRouteWithChildren
  '/speakers': typeof AuthenticatedSpeakersRouteWithChildren
  '/transport': typeof AuthenticatedTransportRoute
  '/waitlist': typeof AuthenticatedWaitlistRoute
  '/api/chat': typeof ApiChatRoute
  '/admin/accommodations': typeof AuthenticatedAdminAccommodationsRoute
  '/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/admin/emergency': typeof AuthenticatedAdminEmergencyRoute
  '/admin/menu': typeof AuthenticatedAdminMenuRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/sessions': typeof AuthenticatedAdminSessionsRoute
  '/admin/speakers': typeof AuthenticatedAdminSpeakersRoute
  '/admin/ushers': typeof AuthenticatedAdminUshersRoute
  '/concierge/food': typeof AuthenticatedConciergeFoodRoute
  '/concierge/orders': typeof AuthenticatedConciergeOrdersRoute
  '/concierge/usher': typeof AuthenticatedConciergeUsherRoute
  '/network/$userId': typeof AuthenticatedNetworkUserIdRoute
  '/schedule/$sessionId': typeof AuthenticatedScheduleSessionIdRoute
  '/speakers/$speakerId': typeof AuthenticatedSpeakersSpeakerIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/concierge': typeof AuthenticatedConciergeIndexRoute
  '/network/room/$roomId': typeof AuthenticatedNetworkRoomRoomIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/about': typeof AuthenticatedAboutRoute
  '/_authenticated/accommodation': typeof AuthenticatedAccommodationRoute
  '/_authenticated/announcements': typeof AuthenticatedAnnouncementsRoute
  '/_authenticated/chatbot': typeof AuthenticatedChatbotRoute
  '/_authenticated/concierge': typeof AuthenticatedConciergeRouteWithChildren
  '/_authenticated/directions': typeof AuthenticatedDirectionsRoute
  '/_authenticated/emergency': typeof AuthenticatedEmergencyRoute
  '/_authenticated/faq': typeof AuthenticatedFaqRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/maidguide': typeof AuthenticatedMaidguideRoute
  '/_authenticated/map': typeof AuthenticatedMapRoute
  '/_authenticated/more': typeof AuthenticatedMoreRoute
  '/_authenticated/nearby': typeof AuthenticatedNearbyRoute
  '/_authenticated/network': typeof AuthenticatedNetworkRouteWithChildren
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/schedule': typeof AuthenticatedScheduleRouteWithChildren
  '/_authenticated/speakers': typeof AuthenticatedSpeakersRouteWithChildren
  '/_authenticated/transport': typeof AuthenticatedTransportRoute
  '/_authenticated/waitlist': typeof AuthenticatedWaitlistRoute
  '/api/chat': typeof ApiChatRoute
  '/_authenticated/admin/accommodations': typeof AuthenticatedAdminAccommodationsRoute
  '/_authenticated/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/_authenticated/admin/emergency': typeof AuthenticatedAdminEmergencyRoute
  '/_authenticated/admin/menu': typeof AuthenticatedAdminMenuRoute
  '/_authenticated/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/_authenticated/admin/sessions': typeof AuthenticatedAdminSessionsRoute
  '/_authenticated/admin/speakers': typeof AuthenticatedAdminSpeakersRoute
  '/_authenticated/admin/ushers': typeof AuthenticatedAdminUshersRoute
  '/_authenticated/concierge/food': typeof AuthenticatedConciergeFoodRoute
  '/_authenticated/concierge/orders': typeof AuthenticatedConciergeOrdersRoute
  '/_authenticated/concierge/usher': typeof AuthenticatedConciergeUsherRoute
  '/_authenticated/network/$userId': typeof AuthenticatedNetworkUserIdRoute
  '/_authenticated/schedule/$sessionId': typeof AuthenticatedScheduleSessionIdRoute
  '/_authenticated/speakers/$speakerId': typeof AuthenticatedSpeakersSpeakerIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/concierge/': typeof AuthenticatedConciergeIndexRoute
  '/_authenticated/network/room/$roomId': typeof AuthenticatedNetworkRoomRoomIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/about'
    | '/accommodation'
    | '/announcements'
    | '/chatbot'
    | '/concierge'
    | '/directions'
    | '/emergency'
    | '/faq'
    | '/home'
    | '/maidguide'
    | '/map'
    | '/more'
    | '/nearby'
    | '/network'
    | '/profile'
    | '/schedule'
    | '/speakers'
    | '/transport'
    | '/waitlist'
    | '/api/chat'
    | '/admin/accommodations'
    | '/admin/announcements'
    | '/admin/emergency'
    | '/admin/menu'
    | '/admin/orders'
    | '/admin/sessions'
    | '/admin/speakers'
    | '/admin/ushers'
    | '/concierge/food'
    | '/concierge/orders'
    | '/concierge/usher'
    | '/network/$userId'
    | '/schedule/$sessionId'
    | '/speakers/$speakerId'
    | '/admin/'
    | '/concierge/'
    | '/network/room/$roomId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/about'
    | '/accommodation'
    | '/announcements'
    | '/chatbot'
    | '/directions'
    | '/emergency'
    | '/faq'
    | '/home'
    | '/maidguide'
    | '/map'
    | '/more'
    | '/nearby'
    | '/network'
    | '/profile'
    | '/schedule'
    | '/speakers'
    | '/transport'
    | '/waitlist'
    | '/api/chat'
    | '/admin/accommodations'
    | '/admin/announcements'
    | '/admin/emergency'
    | '/admin/menu'
    | '/admin/orders'
    | '/admin/sessions'
    | '/admin/speakers'
    | '/admin/ushers'
    | '/concierge/food'
    | '/concierge/orders'
    | '/concierge/usher'
    | '/network/$userId'
    | '/schedule/$sessionId'
    | '/speakers/$speakerId'
    | '/admin'
    | '/concierge'
    | '/network/room/$roomId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/about'
    | '/_authenticated/accommodation'
    | '/_authenticated/announcements'
    | '/_authenticated/chatbot'
    | '/_authenticated/concierge'
    | '/_authenticated/directions'
    | '/_authenticated/emergency'
    | '/_authenticated/faq'
    | '/_authenticated/home'
    | '/_authenticated/maidguide'
    | '/_authenticated/map'
    | '/_authenticated/more'
    | '/_authenticated/nearby'
    | '/_authenticated/network'
    | '/_authenticated/profile'
    | '/_authenticated/schedule'
    | '/_authenticated/speakers'
    | '/_authenticated/transport'
    | '/_authenticated/waitlist'
    | '/api/chat'
    | '/_authenticated/admin/accommodations'
    | '/_authenticated/admin/announcements'
    | '/_authenticated/admin/emergency'
    | '/_authenticated/admin/menu'
    | '/_authenticated/admin/orders'
    | '/_authenticated/admin/sessions'
    | '/_authenticated/admin/speakers'
    | '/_authenticated/admin/ushers'
    | '/_authenticated/concierge/food'
    | '/_authenticated/concierge/orders'
    | '/_authenticated/concierge/usher'
    | '/_authenticated/network/$userId'
    | '/_authenticated/schedule/$sessionId'
    | '/_authenticated/speakers/$speakerId'
    | '/_authenticated/admin/'
    | '/_authenticated/concierge/'
    | '/_authenticated/network/room/$roomId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/waitlist': {
      id: '/_authenticated/waitlist'
      path: '/waitlist'
      fullPath: '/waitlist'
      preLoaderRoute: typeof AuthenticatedWaitlistRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transport': {
      id: '/_authenticated/transport'
      path: '/transport'
      fullPath: '/transport'
      preLoaderRoute: typeof AuthenticatedTransportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/speakers': {
      id: '/_authenticated/speakers'
      path: '/speakers'
      fullPath: '/speakers'
      preLoaderRoute: typeof AuthenticatedSpeakersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/schedule': {
      id: '/_authenticated/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AuthenticatedScheduleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/network': {
      id: '/_authenticated/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof AuthenticatedNetworkRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nearby': {
      id: '/_authenticated/nearby'
      path: '/nearby'
      fullPath: '/nearby'
      preLoaderRoute: typeof AuthenticatedNearbyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/more': {
      id: '/_authenticated/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof AuthenticatedMoreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/map': {
      id: '/_authenticated/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof AuthenticatedMapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/maidguide': {
      id: '/_authenticated/maidguide'
      path: '/maidguide'
      fullPath: '/maidguide'
      preLoaderRoute: typeof AuthenticatedMaidguideRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/faq': {
      id: '/_authenticated/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof AuthenticatedFaqRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/emergency': {
      id: '/_authenticated/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof AuthenticatedEmergencyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/directions': {
      id: '/_authenticated/directions'
      path: '/directions'
      fullPath: '/directions'
      preLoaderRoute: typeof AuthenticatedDirectionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/concierge': {
      id: '/_authenticated/concierge'
      path: '/concierge'
      fullPath: '/concierge'
      preLoaderRoute: typeof AuthenticatedConciergeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chatbot': {
      id: '/_authenticated/chatbot'
      path: '/chatbot'
      fullPath: '/chatbot'
      preLoaderRoute: typeof AuthenticatedChatbotRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/announcements': {
      id: '/_authenticated/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AuthenticatedAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accommodation': {
      id: '/_authenticated/accommodation'
      path: '/accommodation'
      fullPath: '/accommodation'
      preLoaderRoute: typeof AuthenticatedAccommodationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/about': {
      id: '/_authenticated/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AuthenticatedAboutRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/concierge/': {
      id: '/_authenticated/concierge/'
      path: '/'
      fullPath: '/concierge/'
      preLoaderRoute: typeof AuthenticatedConciergeIndexRouteImport
      parentRoute: typeof AuthenticatedConciergeRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/speakers/$speakerId': {
      id: '/_authenticated/speakers/$speakerId'
      path: '/$speakerId'
      fullPath: '/speakers/$speakerId'
      preLoaderRoute: typeof AuthenticatedSpeakersSpeakerIdRouteImport
      parentRoute: typeof AuthenticatedSpeakersRoute
    }
    '/_authenticated/schedule/$sessionId': {
      id: '/_authenticated/schedule/$sessionId'
      path: '/$sessionId'
      fullPath: '/schedule/$sessionId'
      preLoaderRoute: typeof AuthenticatedScheduleSessionIdRouteImport
      parentRoute: typeof AuthenticatedScheduleRoute
    }
    '/_authenticated/network/$userId': {
      id: '/_authenticated/network/$userId'
      path: '/$userId'
      fullPath: '/network/$userId'
      preLoaderRoute: typeof AuthenticatedNetworkUserIdRouteImport
      parentRoute: typeof AuthenticatedNetworkRoute
    }
    '/_authenticated/concierge/usher': {
      id: '/_authenticated/concierge/usher'
      path: '/usher'
      fullPath: '/concierge/usher'
      preLoaderRoute: typeof AuthenticatedConciergeUsherRouteImport
      parentRoute: typeof AuthenticatedConciergeRoute
    }
    '/_authenticated/concierge/orders': {
      id: '/_authenticated/concierge/orders'
      path: '/orders'
      fullPath: '/concierge/orders'
      preLoaderRoute: typeof AuthenticatedConciergeOrdersRouteImport
      parentRoute: typeof AuthenticatedConciergeRoute
    }
    '/_authenticated/concierge/food': {
      id: '/_authenticated/concierge/food'
      path: '/food'
      fullPath: '/concierge/food'
      preLoaderRoute: typeof AuthenticatedConciergeFoodRouteImport
      parentRoute: typeof AuthenticatedConciergeRoute
    }
    '/_authenticated/admin/ushers': {
      id: '/_authenticated/admin/ushers'
      path: '/ushers'
      fullPath: '/admin/ushers'
      preLoaderRoute: typeof AuthenticatedAdminUshersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/speakers': {
      id: '/_authenticated/admin/speakers'
      path: '/speakers'
      fullPath: '/admin/speakers'
      preLoaderRoute: typeof AuthenticatedAdminSpeakersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/sessions': {
      id: '/_authenticated/admin/sessions'
      path: '/sessions'
      fullPath: '/admin/sessions'
      preLoaderRoute: typeof AuthenticatedAdminSessionsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/orders': {
      id: '/_authenticated/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AuthenticatedAdminOrdersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/menu': {
      id: '/_authenticated/admin/menu'
      path: '/menu'
      fullPath: '/admin/menu'
      preLoaderRoute: typeof AuthenticatedAdminMenuRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/emergency': {
      id: '/_authenticated/admin/emergency'
      path: '/emergency'
      fullPath: '/admin/emergency'
      preLoaderRoute: typeof AuthenticatedAdminEmergencyRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/announcements': {
      id: '/_authenticated/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AuthenticatedAdminAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/accommodations': {
      id: '/_authenticated/admin/accommodations'
      path: '/accommodations'
      fullPath: '/admin/accommodations'
      preLoaderRoute: typeof AuthenticatedAdminAccommodationsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/network/room/$roomId': {
      id: '/_authenticated/network/room/$roomId'
      path: '/room/$roomId'
      fullPath: '/network/room/$roomId'
      preLoaderRoute: typeof AuthenticatedNetworkRoomRoomIdRouteImport
      parentRoute: typeof AuthenticatedNetworkRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAccommodationsRoute: typeof AuthenticatedAdminAccommodationsRoute
  AuthenticatedAdminAnnouncementsRoute: typeof AuthenticatedAdminAnnouncementsRoute
  AuthenticatedAdminEmergencyRoute: typeof AuthenticatedAdminEmergencyRoute
  AuthenticatedAdminMenuRoute: typeof AuthenticatedAdminMenuRoute
  AuthenticatedAdminOrdersRoute: typeof AuthenticatedAdminOrdersRoute
  AuthenticatedAdminSessionsRoute: typeof AuthenticatedAdminSessionsRoute
  AuthenticatedAdminSpeakersRoute: typeof AuthenticatedAdminSpeakersRoute
  AuthenticatedAdminUshersRoute: typeof AuthenticatedAdminUshersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAccommodationsRoute:
      AuthenticatedAdminAccommodationsRoute,
    AuthenticatedAdminAnnouncementsRoute: AuthenticatedAdminAnnouncementsRoute,
    AuthenticatedAdminEmergencyRoute: AuthenticatedAdminEmergencyRoute,
    AuthenticatedAdminMenuRoute: AuthenticatedAdminMenuRoute,
    AuthenticatedAdminOrdersRoute: AuthenticatedAdminOrdersRoute,
    AuthenticatedAdminSessionsRoute: AuthenticatedAdminSessionsRoute,
    AuthenticatedAdminSpeakersRoute: AuthenticatedAdminSpeakersRoute,
    AuthenticatedAdminUshersRoute: AuthenticatedAdminUshersRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedConciergeRouteChildren {
  AuthenticatedConciergeFoodRoute: typeof AuthenticatedConciergeFoodRoute
  AuthenticatedConciergeOrdersRoute: typeof AuthenticatedConciergeOrdersRoute
  AuthenticatedConciergeUsherRoute: typeof AuthenticatedConciergeUsherRoute
  AuthenticatedConciergeIndexRoute: typeof AuthenticatedConciergeIndexRoute
}

const AuthenticatedConciergeRouteChildren: AuthenticatedConciergeRouteChildren =
  {
    AuthenticatedConciergeFoodRoute: AuthenticatedConciergeFoodRoute,
    AuthenticatedConciergeOrdersRoute: AuthenticatedConciergeOrdersRoute,
    AuthenticatedConciergeUsherRoute: AuthenticatedConciergeUsherRoute,
    AuthenticatedConciergeIndexRoute: AuthenticatedConciergeIndexRoute,
  }

const AuthenticatedConciergeRouteWithChildren =
  AuthenticatedConciergeRoute._addFileChildren(
    AuthenticatedConciergeRouteChildren,
  )

interface AuthenticatedNetworkRouteChildren {
  AuthenticatedNetworkUserIdRoute: typeof AuthenticatedNetworkUserIdRoute
  AuthenticatedNetworkRoomRoomIdRoute: typeof AuthenticatedNetworkRoomRoomIdRoute
}

const AuthenticatedNetworkRouteChildren: AuthenticatedNetworkRouteChildren = {
  AuthenticatedNetworkUserIdRoute: AuthenticatedNetworkUserIdRoute,
  AuthenticatedNetworkRoomRoomIdRoute: AuthenticatedNetworkRoomRoomIdRoute,
}

const AuthenticatedNetworkRouteWithChildren =
  AuthenticatedNetworkRoute._addFileChildren(AuthenticatedNetworkRouteChildren)

interface AuthenticatedScheduleRouteChildren {
  AuthenticatedScheduleSessionIdRoute: typeof AuthenticatedScheduleSessionIdRoute
}

const AuthenticatedScheduleRouteChildren: AuthenticatedScheduleRouteChildren = {
  AuthenticatedScheduleSessionIdRoute: AuthenticatedScheduleSessionIdRoute,
}

const AuthenticatedScheduleRouteWithChildren =
  AuthenticatedScheduleRoute._addFileChildren(
    AuthenticatedScheduleRouteChildren,
  )

interface AuthenticatedSpeakersRouteChildren {
  AuthenticatedSpeakersSpeakerIdRoute: typeof AuthenticatedSpeakersSpeakerIdRoute
}

const AuthenticatedSpeakersRouteChildren: AuthenticatedSpeakersRouteChildren = {
  AuthenticatedSpeakersSpeakerIdRoute: AuthenticatedSpeakersSpeakerIdRoute,
}

const AuthenticatedSpeakersRouteWithChildren =
  AuthenticatedSpeakersRoute._addFileChildren(
    AuthenticatedSpeakersRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedAboutRoute: typeof AuthenticatedAboutRoute
  AuthenticatedAccommodationRoute: typeof AuthenticatedAccommodationRoute
  AuthenticatedAnnouncementsRoute: typeof AuthenticatedAnnouncementsRoute
  AuthenticatedChatbotRoute: typeof AuthenticatedChatbotRoute
  AuthenticatedConciergeRoute: typeof AuthenticatedConciergeRouteWithChildren
  AuthenticatedDirectionsRoute: typeof AuthenticatedDirectionsRoute
  AuthenticatedEmergencyRoute: typeof AuthenticatedEmergencyRoute
  AuthenticatedFaqRoute: typeof AuthenticatedFaqRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedMaidguideRoute: typeof AuthenticatedMaidguideRoute
  AuthenticatedMapRoute: typeof AuthenticatedMapRoute
  AuthenticatedMoreRoute: typeof AuthenticatedMoreRoute
  AuthenticatedNearbyRoute: typeof AuthenticatedNearbyRoute
  AuthenticatedNetworkRoute: typeof AuthenticatedNetworkRouteWithChildren
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedScheduleRoute: typeof AuthenticatedScheduleRouteWithChildren
  AuthenticatedSpeakersRoute: typeof AuthenticatedSpeakersRouteWithChildren
  AuthenticatedTransportRoute: typeof AuthenticatedTransportRoute
  AuthenticatedWaitlistRoute: typeof AuthenticatedWaitlistRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedAboutRoute: AuthenticatedAboutRoute,
  AuthenticatedAccommodationRoute: AuthenticatedAccommodationRoute,
  AuthenticatedAnnouncementsRoute: AuthenticatedAnnouncementsRoute,
  AuthenticatedChatbotRoute: AuthenticatedChatbotRoute,
  AuthenticatedConciergeRoute: AuthenticatedConciergeRouteWithChildren,
  AuthenticatedDirectionsRoute: AuthenticatedDirectionsRoute,
  AuthenticatedEmergencyRoute: AuthenticatedEmergencyRoute,
  AuthenticatedFaqRoute: AuthenticatedFaqRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedMaidguideRoute: AuthenticatedMaidguideRoute,
  AuthenticatedMapRoute: AuthenticatedMapRoute,
  AuthenticatedMoreRoute: AuthenticatedMoreRoute,
  AuthenticatedNearbyRoute: AuthenticatedNearbyRoute,
  AuthenticatedNetworkRoute: AuthenticatedNetworkRouteWithChildren,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedScheduleRoute: AuthenticatedScheduleRouteWithChildren,
  AuthenticatedSpeakersRoute: AuthenticatedSpeakersRouteWithChildren,
  AuthenticatedTransportRoute: AuthenticatedTransportRoute,
  AuthenticatedWaitlistRoute: AuthenticatedWaitlistRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
